version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: PostHub-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
      - MONGO_INITDB_DATABASE=postHub
    ports:
      - "27017:27017"